"use client";
import Link from "next/link"; import { useEffect,useState } from "react"; import { Package,ArrowDownToLine,ArrowUpFromLine,ClipboardList,Plus,Minus,TriangleAlert } from "lucide-react";
import type {DashboardData} from "@/lib/types"; import {Loading,Empty} from "@/components/ui"; import {MovementChart,CompareChart,RankingChart} from "@/components/charts"; import {formatDate} from "@/lib/date";
export default function Dashboard(){const [data,setData]=useState<DashboardData|null>(null);useEffect(()=>{fetch('/api/dashboard',{cache:'no-store'}).then(r=>r.json()).then(setData)},[]);if(!data)return <Loading/>;const cards=[["Estoque atual",data.stock,"Disponíveis no estoque",Package,"green"],["Entradas no mês",data.monthEntries,"Cestas recebidas",ArrowDownToLine,"green"],["Retiradas no mês",data.monthExits,"Cestas entregues",ArrowUpFromLine,"red"],["Solicitações",data.requests,"Retiradas realizadas",ClipboardList,"dark"]] as const;return <div className="fade-in"><div className="page-head"><div><p className="eyebrow">VISÃO GERAL</p><h2>Olá, bom dia!</h2><p>Acompanhe o estoque e as movimentações deste mês.</p></div><div className="quick"><Link className="btn" href="/entrada"><Plus size={18}/>Registrar entrada</Link><Link className="btn danger" href="/retirada"><Minus size={18}/>Registrar retirada</Link></div></div>
 {data.stock<=data.minimumStock&&<div className="alert"><TriangleAlert/><div><strong>Estoque baixo</strong><p>Restam apenas {data.stock} cestas. O mínimo configurado é {data.minimumStock}.</p></div></div>}
 <div className="stats">{cards.map(([label,value,sub,Icon,color],i)=><article className="stat" key={label} style={{animationDelay:`${i*70}ms`}}><div className={`stat-icon ${color}`}><Icon/></div><p>{label}</p><strong>{value} <small>cestas</small></strong><span>{sub}</span></article>)}</div>
 <section className="panel wide"><div className="panel-title"><div><p className="eyebrow">DESEMPENHO</p><h3>Movimentação mensal</h3></div><span className="pill">Mês atual</span></div>{data.daily.length?<MovementChart data={data.daily}/>:<Empty text="Registre movimentações para visualizar o gráfico."/>}</section>
 <div className="grid-3"><section className="panel"><h3>Entradas x Saídas</h3><CompareChart entries={data.monthEntries} exits={data.monthExits}/></section><section className="panel"><h3>Retiradas por técnico</h3>{data.technicians.length?<RankingChart data={data.technicians}/>:<Empty/>}</section><section className="panel"><h3>Retiradas por destino</h3>{data.destinations.length?<RankingChart data={data.destinations} color="#263a30"/>:<Empty/>}</section></div>
 <section className="panel"><div className="panel-title"><h3>Últimas movimentações</h3><Link href="/movimentacoes" className="text-link">Ver histórico completo →</Link></div><div className="table-wrap"><table><thead><tr><th>Tipo</th><th>Quantidade</th><th>Técnico</th><th>Destino</th><th>Data</th><th>Hora</th></tr></thead><tbody>{data.movements.slice(0,7).map(m=><tr key={m.id}><td><span className={`type ${m.type.toLowerCase()}`}>{m.type}</span></td><td className={m.type==='ENTRADA'?'positive':m.type==='SAIDA'?'negative':''}>{m.type==='ENTRADA'?'+':m.type==='SAIDA'?'-':''}{m.quantity}</td><td>{m.technician||'—'}</td><td>{m.destination||'—'}</td><td>{formatDate(m.date)}</td><td>{m.time}</td></tr>)}</tbody></table>{!data.movements.length&&<Empty/>}</div></section></div>}
