"use client";
import { useCallback, useEffect, useState } from "react"; import { useRouter } from "next/navigation"; import { CheckCircle2, ArrowDownToLine, ArrowUpFromLine, Package } from "lucide-react"; import { Modal, useToast } from "./ui";
const now=()=>{const d=new Date();return {date:d.toLocaleDateString("sv-SE"),time:d.toTimeString().slice(0,5)}};
export function MovementForm({type}:{type:"ENTRADA"|"SAIDA"}){const initial=now();const router=useRouter();const toast=useToast();const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState(false);const [form,setForm]=useState({quantity:"",technician:"",destination:"",date:initial.date,time:initial.time,notes:""});
 const [stock,setStock]=useState<number|null>(null);
 const loadStock=useCallback(()=>{fetch('/api/stock',{cache:'no-store'}).then(r=>r.json()).then(d=>setStock(d.stock)).catch(()=>setStock(null))},[]);
 useEffect(()=>{loadStock()},[loadStock]);
 const isExit=type==="SAIDA"; const update=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 async function submit(){setBusy(true);try{const res=await fetch('/api/movements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,quantity:Number(form.quantity),technician:form.technician,destination:form.destination,date:form.date,time:form.time,notes:form.notes})});const data=await res.json();if(!res.ok)throw new Error(data.error);toast.show(`${isExit?'Retirada':'Entrada'} de ${form.quantity} cesta${Number(form.quantity)>1?'s':''} registrada com sucesso.`);setForm({...form,quantity:"",technician:"",destination:"",notes:""});setConfirm(false);loadStock();router.refresh()}catch(e){toast.show(e instanceof Error?e.message:'Erro ao registrar.','error');loadStock()}finally{setBusy(false)}}
 function validate(e:React.FormEvent){e.preventDefault();if(!Number.isInteger(Number(form.quantity))||Number(form.quantity)<=0){toast.show('Informe uma quantidade inteira maior que zero.','error');return}if(isExit&&(!form.technician.trim()||!form.destination.trim())){toast.show('Preencha o técnico e o destino.','error');return}if(isExit&&stock!==null&&Number(form.quantity)>stock){toast.show(`Estoque insuficiente. Existem apenas ${stock} cestas disponíveis no estoque.`,'error');return}isExit?setConfirm(true):submit()}
 return <><section className="form-card"><div className={`form-hero ${isExit?'exit':''}`}>{isExit?<ArrowUpFromLine/>:<ArrowDownToLine/>}<div><h2>{isExit?'Registrar Retirada':'Registrar Entrada'}</h2><p>{isExit?'Informe quem retirou e para onde as cestas serão destinadas.':'Adicione ao estoque as cestas recebidas.'}</p></div>{stock!==null&&<div className="stock-badge"><Package size={18}/><span><small>Disponível</small><strong>{stock} cesta{stock===1?'':'s'}</strong></span></div>}</div><form onSubmit={validate} className="form-grid">
 {isExit&&<label className="full">Nome do técnico<span>*</span><input value={form.technician} onChange={e=>update('technician',e.target.value)} placeholder="Ex.: João da Silva" required/></label>}
 <label>Quantidade de cestas<span>*</span><input type="number" min="1" step="1" max={isExit&&stock!==null?Math.max(stock,1):undefined} value={form.quantity} onChange={e=>update('quantity',e.target.value)} placeholder="0" required/></label>
 {isExit&&<label>Destino<span>*</span><input value={form.destination} onChange={e=>update('destination',e.target.value)} placeholder="Ex.: CRAS Centro" required/></label>}
 <label>Data<span>*</span><input type="date" value={form.date} onChange={e=>update('date',e.target.value)} required/></label><label>Hora<span>*</span><input type="time" value={form.time} onChange={e=>update('time',e.target.value)} required/></label>
 <label className="full">{isExit?'Observações':'Origem / Observação'}<textarea value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder={isExit?'Informação adicional (opcional)':'Ex.: Entrega semanal (opcional)'}/></label>
 <div className="form-actions full"><button className={`btn ${isExit?'danger':''}`} disabled={busy}>{isExit?'Confirmar Retirada':'Registrar Entrada'}</button></div></form></section>{toast.node}
 {confirm&&<Modal title="Confirmar retirada?" onClose={()=>setConfirm(false)}><div className="summary"><div><small>Técnico</small><strong>{form.technician}</strong></div><div><small>Quantidade</small><strong>{form.quantity} cesta(s)</strong></div><div><small>Destino</small><strong>{form.destination}</strong></div><div><small>Data e hora</small><strong>{form.date.split('-').reverse().join('/')} às {form.time}</strong></div></div><div className="modal-actions"><button className="btn secondary" onClick={()=>setConfirm(false)}>Cancelar</button><button className="btn danger" onClick={submit} disabled={busy}><CheckCircle2 size={18}/>{busy?'Registrando...':'Confirmar retirada'}</button></div></Modal>}</>}
